name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pybuild-deps
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # Required for pushing tags - https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.13"

      - name: Upgrade pip
        run: |
          pip install --constraint="$(pwd)/.github/workflows/constraints.txt" pip
          pip --version

      - name: Install Poetry
        run: |
          pip install --constraint="$(pwd)/.github/workflows/constraints.txt" poetry
          poetry --version

      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          echo "sha=$(git rev-parse --verify --quiet HEAD^)" >> $GITHUB_OUTPUT

      - name: Check version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        run: |
          echo "version=$(poetry version -s)" >> $GITHUB_OUTPUT

      - name: Tag new version if it doesn't exist
        id: tag-version
        if: steps.check-version.outputs.version
        uses: bruno-fs/repo-tagger@1.0.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag: "${{ steps.check-version.outputs.version }}"

      - name: Bump version for developmental release
        if: "! steps.tag-version.outputs.tag"
        run: |
          poetry version patch &&
          version=$(poetry version -s) &&
          poetry version $version.dev.$(date +%s)

      - name: Build package
        run: |
          poetry build --ansi

      - name: Publish package on PyPI
        if: steps.tag-version.outputs.tag
        uses: pypa/gh-action-pypi-publish@v1.10.0

      - name: Publish package on TestPyPI
        if: "! steps.tag-version.outputs.tag"
        uses: pypa/gh-action-pypi-publish@v1.10.0
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish the release notes
        uses: release-drafter/release-drafter@v6.0.0
        with:
          publish: ${{ steps.tag-version.outputs.tag != '' }}
          tag: ${{ steps.tag-version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
